/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import project.BLL;
import project.Donor;
import project.Needy;
import project.Organization;

/**
 *
 * @author Faizan
 */
public class orgNeedyAndDons extends javax.swing.JFrame {

    Organization o;
    /**
     * Creates new form orgNeedyAndDons
     */
    public orgNeedyAndDons() {
        initComponents();
    }
    
     public orgNeedyAndDons(Organization o1) {
        initComponents();
        o=o1;
        orgName.setText(o.name);
        DefaultListModel donModel = new DefaultListModel();
        DefaultListModel needyModel = new DefaultListModel();
        BLL b=BLL.getInstance();
        List<Donor> dons=b.OrganizationDonors(o);
        for(int i=0;i<dons.size();i++)
        {
            donModel.addElement(dons.get(i).donPerson.name);
        }
        donList.setModel(donModel);
          List<Needy> needy=b.OrganizationNeedy(o);
        for(int i=0;i<needy.size();i++)
        {
            needyModel.addElement(needy.get(i).needyPerson.name);
        }
        recList.setModel(needyModel);
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orgName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        donList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        recList = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        donName = new javax.swing.JTextField();
        donSearch = new javax.swing.JButton();
        needyText = new javax.swing.JTextField();
        needySearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(donList);

        jScrollPane2.setViewportView(recList);

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        donSearch.setText("Search Donor");
        donSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donSearchActionPerformed(evt);
            }
        });

        needySearch.setText("Search Beneficiary");
        needySearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                needySearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(orgName, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(donName)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(needyText))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(donSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addComponent(needySearch)
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(orgName, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(donName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(needyText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(donSearch)
                    .addComponent(needySearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void donSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donSearchActionPerformed

        String name=donName.getText();
        BLL b=BLL.getInstance();
        Donor don=b.findDonor(name);
        if(don!=null)
        {
            DonorDetails dd=new DonorDetails(o,don);
            this.setVisible(false);
            dd.setVisible(true);
        }
        else
        {
               JOptionPane.showMessageDialog(null, "Could not find Donor");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_donSearchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Project p1=new Project(o);
        this.setVisible(false);
        p1.setVisible(true);


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void needySearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_needySearchActionPerformed

          String name=needyText.getText();
        BLL b=BLL.getInstance();
        Needy needy=b.findNeedy(name);
        if(needy!=null){
        NeedyDetails nd=new NeedyDetails(o,needy);
        this.setVisible(false);
        nd.setVisible(true);
        }
        else
               JOptionPane.showMessageDialog(null, "Could not find Beneficiary");
        // TODO add your handling code here:
    }//GEN-LAST:event_needySearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(orgNeedyAndDons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(orgNeedyAndDons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(orgNeedyAndDons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(orgNeedyAndDons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new orgNeedyAndDons().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> donList;
    private javax.swing.JTextField donName;
    private javax.swing.JButton donSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton needySearch;
    private javax.swing.JTextField needyText;
    private javax.swing.JLabel orgName;
    private javax.swing.JList<String> recList;
    // End of variables declaration//GEN-END:variables
}
